<a href="https://colab.research.google.com/github/akarshpyr/Akarshcodes12/blob/main/Pandas_work_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'Temperature':['hot','cold','warm','dry'],'Weather':['bad','sexy','okay','dead']})

In [3]:
df

Temperature Weather
0         hot     bad
1        cold    sexy
2        warm    okay
3         dry    dead

In [4]:
df1 = pd.get_dummies(df)

In [5]:
df1

Temperature_cold  Temperature_dry  Temperature_hot  Temperature_warm  \
0                 0                0                1                 0   
1                 1                0                0                 0   
2                 0                0                0                 1   
3                 0                1                0                 0   

   Weather_bad  Weather_dead  Weather_okay  Weather_sexy  
0            1             0             0             0  
1            0             0             0             1  
2            0             0             1             0  
3            0             1             0             0

In [6]:
df2 = pd.DataFrame({'age':[0,10,2,3,4,5,61,20,21,22,34,59,34,22,12,21,23,4,34,89,33,34,21,27,26]})

In [7]:
df2

age
0     0
1    10
2     2
3     3
4     4
5     5
6    61
7    20
8    21
9    22
10   34
11   59
12   34
13   22
14   12
15   21
16   23
17    4
18   34
19   89
20   33
21   34
22   21
23   27
24   26

In [8]:
bins = [0,25,50,100]
labels = ['children','dead_people_alive','almost_dead']
df2['age_group'] = pd.cut(x=df2['age'],bins=bins,labels=labels,include_lowest=True)

In [9]:
df2

age          age_group
0     0           children
1    10           children
2     2           children
3     3           children
4     4           children
5     5           children
6    61        almost_dead
7    20           children
8    21           children
9    22           children
10   34  dead_people_alive
11   59        almost_dead
12   34  dead_people_alive
13   22           children
14   12           children
15   21           children
16   23           children
17    4           children
18   34  dead_people_alive
19   89        almost_dead
20   33  dead_people_alive
21   34  dead_people_alive
22   21           children
23   27  dead_people_alive
24   26  dead_people_alive

In [10]:
A = np.random.randint(3,4)
B = np.random.randint(4)

In [11]:
A1 = np.random.rand(3,4)
B1 = np.random.rand(4)

In [12]:
A1

array([[0.69762762, 0.12236637, 0.60485156, 0.47606463],
       [0.62518247, 0.08186436, 0.2604182 , 0.06558094],
       [0.86705366, 0.27225313, 0.98015557, 0.71574954]])

In [13]:
A1.shape

(3, 4)

In [14]:
B1

array([0.14181681, 0.8752264 , 0.89473866, 0.50356565])

Number of columns is fixed while giving the shape in broadcasting

In [15]:
B_broadcast = np.broadcast_to(B1,(5,4))

In [16]:
B_broadcast

array([[0.14181681, 0.8752264 , 0.89473866, 0.50356565],
       [0.14181681, 0.8752264 , 0.89473866, 0.50356565],
       [0.14181681, 0.8752264 , 0.89473866, 0.50356565],
       [0.14181681, 0.8752264 , 0.89473866, 0.50356565],
       [0.14181681, 0.8752264 , 0.89473866, 0.50356565]])

In [17]:
my_list = [1,2,3,4,5]
a = np.array(my_list)

In [18]:
a

array([1, 2, 3, 4, 5])

In [19]:
matr = [[1,2,3],[1,22,2],[2,23,33]]
b = np.array(matr)

In [20]:
b

array([[ 1,  2,  3],
       [ 1, 22,  2],
       [ 2, 23, 33]])

In [21]:
x = b.shape

In [22]:
x[0]

3

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
assd = np.ones((33,23))

In [27]:
assd*7

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
        7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7.,

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.linspace(0,5,30)

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

In [30]:
np.random.rand(3,3)

array([[0.44041211, 0.29106323, 0.03013584],
       [0.29779393, 0.46373715, 0.55840964],
       [0.35489808, 0.29434258, 0.22314407]])

In [31]:
np.random.randn(2,3)

array([[-0.31734634, -2.1335245 ,  0.29002734],
       [-1.60068616, -0.04805713, -0.89244143]])

In [32]:
z = np.random.randint(1,22,10)

In [33]:
print(z)

[12 15 16  8 21 16  5  1  9  7]


In [34]:
print(z.reshape(5,2))

[[12 15]
 [16  8]
 [21 16]
 [ 5  1]
 [ 9  7]]


In [35]:
z.max()

21

In [36]:
z.argmax() #gives the index of the max number

4

In [37]:
z.argmin()

7

In [38]:
z.dtype

dtype('int64')

In [39]:
a = np.array([2,3,4,5])
b = np.array([2,2,3,4])
c = np.array([2,3,3,3])

In [40]:
a+b+c

array([ 6,  8, 10, 12])

In [41]:
np.add(a,b)

array([4, 5, 7, 9])

In [42]:
c

array([2, 3, 3, 3])

In [43]:
a*b

array([ 4,  6, 12, 20])

In [44]:
np.mean(a)

3.5

In [45]:
np.sum(a)

14

In [46]:
np.average(a)

3.5

In [47]:
np.var(a)

1.25

In [48]:
a = np.arange(10,1,-1.5)

In [49]:
a

array([10. ,  8.5,  7. ,  5.5,  4. ,  2.5])

In [50]:
a[0:]

array([10. ,  8.5,  7. ,  5.5,  4. ,  2.5])

In [51]:
a[0:4]

array([10. ,  8.5,  7. ,  5.5])

In [52]:
a[:3]

array([10. ,  8.5,  7. ])

In [53]:
a[-1:2]

array([], dtype=float64)

In [54]:
a[-1:-3]

array([], dtype=float64)

In [55]:
a[-3:] #lower to higher kodappa

array([5.5, 4. , 2.5])

In [56]:
a[-4::2]

array([7., 4.])

In [57]:
a[2]+a[3]

12.5

In [58]:
a= np.array([[1,2],[3,4],[5,6]])

In [59]:
a[1,0]

3

In [61]:
b = a[[0,1,2],[0,0,1]]

In [62]:
b

array([1, 3, 6])

In [63]:
c = a[[0,1,2],[1,1,0]]

In [64]:
c

array([2, 4, 5])

In [65]:
a = np.array([10,40,20,50,22])

In [66]:
a[a>20]

array([40, 50, 22])

In [67]:
a[a%4==0]*2

array([80, 40])

In [68]:
df1 = pd.DataFrame({'city':['bangalore','chennai','kolkata','shimla'],'state':['karnataka','TN','WB','HP'],'weather':['normal','Hot','humid','cold']})

In [69]:
df2 = pd.DataFrame({'Town':['dabaspet','krishnagiri','gaon','lamla'],'state':['karnataka','TN','WB','HP'],'popu':['7cr','5cr','3cr','2cr']})

In [70]:
df4 = pd.DataFrame({'Town':['dabaspet','krishnagiri','jumma','timma'],'state':['karnataka','TN','WB','HP'],'popu':['7cr','4cr','3cr','2cr']})

In [71]:
df3 = pd.merge(df1,df2,on='state').reset_index(drop=True)

In [72]:
(df3)

city      state weather         Town popu
0  bangalore  karnataka  normal     dabaspet  7cr
1    chennai         TN     Hot  krishnagiri  5cr
2    kolkata         WB   humid         gaon  3cr
3     shimla         HP    cold        lamla  2cr

In [73]:
df3.reset_index(drop=True)

city      state weather         Town popu
0  bangalore  karnataka  normal     dabaspet  7cr
1    chennai         TN     Hot  krishnagiri  5cr
2    kolkata         WB   humid         gaon  3cr
3     shimla         HP    cold        lamla  2cr

In [74]:
df3.set_index('city')

state weather         Town popu
city                                          
bangalore  karnataka  normal     dabaspet  7cr
chennai           TN     Hot  krishnagiri  5cr
kolkata           WB   humid         gaon  3cr
shimla            HP    cold        lamla  2cr

In [75]:
df3 = pd.merge(df1,df2,on='state',how='inner')

In [76]:
df3

city      state weather         Town popu
0  bangalore  karnataka  normal     dabaspet  7cr
1    chennai         TN     Hot  krishnagiri  5cr
2    kolkata         WB   humid         gaon  3cr
3     shimla         HP    cold        lamla  2cr

In [77]:
df = pd.DataFrame({'date1':['2020-12-01','2020-12-02','2020-12-03','2020-12-03'],'date2':['201201','201202','201203','201203'],'store':['a1','b1','c1','d1']})

In [78]:
df

date1   date2 store
0  2020-12-01  201201    a1
1  2020-12-02  201202    b1
2  2020-12-03  201203    c1
3  2020-12-03  201203    d1

In [79]:
df['Sales'] = [3000,2000,2100,2200]

In [80]:
df

date1   date2 store  Sales
0  2020-12-01  201201    a1   3000
1  2020-12-02  201202    b1   2000
2  2020-12-03  201203    c1   2100
3  2020-12-03  201203    d1   2200

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   date1   4 non-null      object
 1   date2   4 non-null      object
 2   store   4 non-null      object
 3   Sales   4 non-null      int64 
dtypes: int64(1), object(3)
memory usage: 256.0+ bytes


In [82]:
df.dtypes

date1    object
date2    object
store    object
Sales     int64
dtype: object

In [83]:
df

date1   date2 store  Sales
0  2020-12-01  201201    a1   3000
1  2020-12-02  201202    b1   2000
2  2020-12-03  201203    c1   2100
3  2020-12-03  201203    d1   2200

In [84]:
df['date1_new'] = pd.to_datetime(df['date1'])

In [85]:
df

date1   date2 store  Sales  date1_new
0  2020-12-01  201201    a1   3000 2020-12-01
1  2020-12-02  201202    b1   2000 2020-12-02
2  2020-12-03  201203    c1   2100 2020-12-03
3  2020-12-03  201203    d1   2200 2020-12-03

In [86]:
df.drop('date1',inplace=True,axis=1)

In [87]:
df

date2 store  Sales  date1_new
0  201201    a1   3000 2020-12-01
1  201202    b1   2000 2020-12-02
2  201203    c1   2100 2020-12-03
3  201203    d1   2200 2020-12-03

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date2      4 non-null      object        
 1   store      4 non-null      object        
 2   Sales      4 non-null      int64         
 3   date1_new  4 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 256.0+ bytes


In [89]:
df['new_date'] = pd.to_datetime(df['date2'])

In [90]:
df

date2 store  Sales  date1_new   new_date
0  201201    a1   3000 2020-12-01 2001-12-20
1  201202    b1   2000 2020-12-02 2002-12-20
2  201203    c1   2100 2020-12-03 2003-12-20
3  201203    d1   2200 2020-12-03 2003-12-20

In [91]:
df.drop('date2',axis=1,inplace=True)

In [92]:
df

store  Sales  date1_new   new_date
0    a1   3000 2020-12-01 2001-12-20
1    b1   2000 2020-12-02 2002-12-20
2    c1   2100 2020-12-03 2003-12-20
3    d1   2200 2020-12-03 2003-12-20

In [93]:
df.dtypes

store                object
Sales                 int64
date1_new    datetime64[ns]
new_date     datetime64[ns]
dtype: object

In [94]:
df['yeard1'] = df['date1_new'].dt.strftime('%Y')

In [95]:
df

store  Sales  date1_new   new_date yeard1
0    a1   3000 2020-12-01 2001-12-20   2020
1    b1   2000 2020-12-02 2002-12-20   2020
2    c1   2100 2020-12-03 2003-12-20   2020
3    d1   2200 2020-12-03 2003-12-20   2020

In [96]:
df['yeard1'] = df['date1_new'].dt.strftime('%d')

In [97]:
df.dtypes

store                object
Sales                 int64
date1_new    datetime64[ns]
new_date     datetime64[ns]
yeard1               object
dtype: object

In [98]:
lst = [1,2,3,4]
type(lst)

list

In [99]:
df11 = pd.DataFrame(lst,columns=['numbers'])

In [100]:
df11

numbers
0        1
1        2
2        3
3        4

In [101]:
df11.dtypes

numbers    int64
dtype: object

In [102]:
df11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   numbers  4 non-null      int64
dtypes: int64(1)
memory usage: 160.0 bytes


In [103]:
arr = df11.to_numpy()

In [104]:
type(arr)

numpy.ndarray

In [105]:
df11 = pd.DataFrame(arr)

In [106]:
df11

0
0  1
1  2
2  3
3  4

In [107]:
arr

array([[1],
       [2],
       [3],
       [4]])

In [108]:
d2 = pd.DataFrame({'name':['aki','anu','ali','avi'],'age':[22,22,21,23],'score':[23,11,22,22]})

In [109]:
d2

name  age  score
0  aki   22     23
1  anu   22     11
2  ali   21     22
3  avi   23     22

In [110]:
print(d2.iterrows())

<generator object DataFrame.iterrows at 0x7fc4be6a6040>


In [111]:
for i,j in d2.iterrows():
  print(i,j)

0 name     aki
age       22
score     23
Name: 0, dtype: object
1 name     anu
age       22
score     11
Name: 1, dtype: object
2 name     ali
age       21
score     22
Name: 2, dtype: object
3 name     avi
age       23
score     22
Name: 3, dtype: object


In [112]:
d2.isnull()

name    age  score
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [113]:
d2.isnull().sum()

name     0
age      0
score    0
dtype: int64

In [114]:
dd = d2.append(df11)

In [115]:
dd

0   age name  score
0  NaN  22.0  aki   23.0
1  NaN  22.0  anu   11.0
2  NaN  21.0  ali   22.0
3  NaN  23.0  avi   22.0
0  1.0   NaN  NaN    NaN
1  2.0   NaN  NaN    NaN
2  3.0   NaN  NaN    NaN
3  4.0   NaN  NaN    NaN

In [116]:
dd.reset_index(drop=True)

0   age name  score
0  NaN  22.0  aki   23.0
1  NaN  22.0  anu   11.0
2  NaN  21.0  ali   22.0
3  NaN  23.0  avi   22.0
4  1.0   NaN  NaN    NaN
5  2.0   NaN  NaN    NaN
6  3.0   NaN  NaN    NaN
7  4.0   NaN  NaN    NaN

In [117]:
dd.head(8)

0   age name  score
0  NaN  22.0  aki   23.0
1  NaN  22.0  anu   11.0
2  NaN  21.0  ali   22.0
3  NaN  23.0  avi   22.0
0  1.0   NaN  NaN    NaN
1  2.0   NaN  NaN    NaN
2  3.0   NaN  NaN    NaN
3  4.0   NaN  NaN    NaN